### ISSUE TITLE
dedicated server crash

### ISSUE THREAD

**Issue by xg787** [DenisMasterHerobrine/TheAfterdark#10]
[latest.log](https://github.com/user-attachments/files/17558092/latest.log)
[debug.log](https://github.com/user-attachments/files/17558094/debug.log)
[crash-2024-10-29_10.07.15-server.txt](https://github.com/user-attachments/files/17558095/crash-2024-10-29_10.07.15-server.txt)

**Comment by VeiTrr** [comment]
fixed, wait for reupload release 1.0.3 in 15-20 minutes
