### ISSUE TITLE
Can't teleport to the afterdark at all

### ISSUE THREAD

**Issue by VIPrecxl490** [DenisMasterHerobrine/TheAfterdark#12]
Every time I interact with a teleport block it just says "This shrine rejects your offering..."

I have tried over 10 naturally generated shrines and then went into creative gamemode and tested a bunchhhhhhh of teleport blocks with the catalyst ofc and always the same output

**Comment by VeiTrr** [comment]
mc version? mod version?  any other mods installed? mod loader?

**Comment by VIPrecxl490** [comment]
> mc version? mod version? any other mods installed? mod loader?

![image](https://github.com/user-attachments/assets/95415161-a88d-4f12-9c0d-4fa456570fa5)
![image](https://github.com/user-attachments/assets/2306b3bb-1af7-4bbd-9471-fe2fe89420ef)

I do have a bunch of other mods installed, although I believe none of those should interfere with The Afterdark

Using Prism Launcher ^^

**Comment by VeiTrr** [comment]
update mod
