### ISSUE TITLE
Client crash when things are on fire

### ISSUE THREAD

**Issue by Gaz492** [DenisMasterHerobrine/TheAfterdark#13]
Playing FTB Evolution and ran into a fire spreading through a forest then ran into a crash.

Crash log: https://pste.me/@XIRugdPvoKk

**Comment by VeiTrr** [comment]
already fixed, redownload the last release from oct 31

**Comment by JohnGlacious** [comment]
[latest.log](https://github.com/user-attachments/files/17654461/latest.log)

Hey there! Wanted to let you know that this still isn't resolved. Here's the log file that contains what happens.

**Comment by DenisMasterHerobrine** [comment]
The crash above was already fixed by the release from October, 31 and is not reproducible. Did you redownloaded the 1.0.3 version where this got already hotfixed?

**Comment by JohnGlacious** [comment]
> The crash above was already fixed by the release from October, 31 and is not reproducible. Did you redownloaded the 1.0.3 version where this got already hotfixed?

Yes I have. This was through the 1.0.3 version. Downloaded it on November 2nd, 2024.

**Comment by VeiTrr** [comment]
> > The crash above was already fixed by the release from October, 31 and is not reproducible. Did you redownloaded the 1.0.3 version where this got already hotfixed?
> 
> Yes I have. This was through the 1.0.3 version. Downloaded it on November 2nd, 2024.

Does this keep happening if only the Afterdark is installed?

**Comment by JohnGlacious** [comment]
> > > The crash above was already fixed by the release from October, 31 and is not reproducible. Did you redownloaded the 1.0.3 version where this got already hotfixed?
> > 
> > 
> > Yes I have. This was through the 1.0.3 version. Downloaded it on November 2nd, 2024.
> 
> Does this keep happening if only the Afterdark is installed?

That would be correct. It's only when Afterdark was installed.

**Comment by VeiTrr** [comment]
> That would be correct. It's only when Afterdark was installed.

if only Afterdark is installed and no other mods are present?

**Comment by JohnGlacious** [comment]
> if only Afterdark is installed and no other mods are present?

Oh I thought you meant if it happens only when Afterdark installed, my apologies. No there's still other mods present.

**Comment by VeiTrr** [comment]
> > if only Afterdark is installed and no other mods are present?
> 
> Oh I thought you meant if it happens only when Afterdark installed, my apologies. No there's still other mods present.

So check if this crash only occurs with Afterdark installed without other mods, and then give feedback. 
No - the problem is in compatibility with another mod (which one?)
Yes - the problem is in Afterdark itself

**Comment by ghost** [comment]
this crash also happened to a player on the all the mods discord where they had added this mod to all the mods 10
https://mclo.gs/TfFQzDz

**Comment by VeiTrr** [comment]
> this crash also happened to a player on the all the mods discord where they had added this mod to all the mods 10 https://mclo.gs/TfFQzDz

he is using 1.0.3 instead of 1.0.3.1
