### ISSUE TITLE
Weird sound bug

### ISSUE THREAD

**Issue by X-Machiavelli** [DenisMasterHerobrine/TheAfterdark#6]
After installing this mod, the sound quality get broken when various sounds are overlapped during the game. uninstalling this mod immediately resolved the stuttering. It's not severe, but it's annoying enough.

neoforge21.1.72, MC1.21.1
The latest version of the mod
I tried verifying with all sound-related mods disabled and the same thing happened. such as 'sound physics remastered'

**Comment by DenisMasterHerobrine** [comment]
We're not modifying nor even interacting with the sound engine, so probably that's not our issue, because me and @VeiTrr cannot reproduce this. Please verify the mod alone and check for any issues with your system sound card. Thank you.
