### ISSUE TITLE
Teleport blocks not loading

### ISSUE THREAD

**Issue by AnAmiablePenguin** [DenisMasterHerobrine/TheAfterdark#8]
Hello! I'm fairly new to Minecraft modding and I was just trying to setup a vanilla+ server for me and a small group of friends. However, whenever a chunk loads with a a teleport block I always get this error message. I have successfully loaded the dimension by spawning the teleport block from creative. We are playing on a 1.21.1 forge server if that helps at all?
![Capture](https://github.com/user-attachments/assets/1fc44cee-cdd2-4298-864c-a519a95440b6)

**Comment by VeiTrr** [comment]
You can ignore this message, 
It is a result of not fully implemented block with Entity class, which will be in future updates.

**Comment by VeiTrr** [comment]
Fixed in 1.0.3
